Millestone 2 basic modules
FrancoRosa/react-calc pull request #2
Opened 2020-10-04 04:10 UTC by FrancoRosa

Hello TSEs,
In this milestone I manage to do:

- Create stateless react modules.
- Specify props types.
- Specify default props.
- Destructuring props.
- Make the basic look of the calculator project.

Thank you in advance for your kind feedback.

2020-10-04 18:46 UTC, jofer86 requested changes
## `const STATUS = "CHANGES REQUIRED"`⚠️ ⚠️ ⚠️ 
## :wave: :wave: Hello! I'm Jorge, and  I will be conducting this code review. Let me get a closer look 🔎 🔍 🔎 🔍 🕵🏼 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- Plsease read the comment below and do the necessary adjustments.
--------------------------------------------------------------------
**Rock on**  🤘🏼 
**_Jorge Fernando Rincón Figueroa._** 
Technical Support Engineer.

2020-10-04 18:46 UTC, jofer86 commented on src/components/App.js
> +export default App;
For this par you need to divide your code into components, That is done in this file, but you should implement once component per file, and then have them come together. The Implementation is fine but your components need to have their own file. Other than that the project meets the criteria, except for that. So just give your components their own file and you're good to go.`

2020-10-04 19:08 UTC, FrancoRosa commented
Hello Fernando,
I forgot to push once I divided the components on its file.
Now, every component lives on its own file
Thank you

2020-10-05 01:04 UTC, shloch approved these changes
## Hello @FrancoRosa 

Great great great.....keep up with the good work
![accomplished](https://user-images.githubusercontent.com/40712459/95031651-0eaa0900-06af-11eb-8d7a-080467fae2ac.jpg)

Now we can design
Happy coding

2020-10-05 01:10 UTC, merged