Milestone 5 calculator
FrancoRosa/react-calc pull request #5
Opened 2020-10-12 06:38 UTC by FrancoRosa

Hello TSEs,
In this milestone I did:

 - Make a statefull version of App module
 - Pass function handlers as props
 - Make a usefull calculator app

Please send me your feedback, so I can improve this project.
Thank you

2020-10-12 14:08 UTC, mikenath223 requested changes
### Hi @FrancoRosa 👋

**You've done well on this buddy. 💪**

However, there are a few changes to be made, kindly make them and submit for a re-review.

- [x] Clicking an example like `9 x 3 =`, then followed by the percentage button`%` produces `NAN`. Kindly fix this

- [ ] Please handle the error from division by zero effectively, as dividing by zero crashes the app.

- [ ] OPTIONAL - Consider using arrow function to setState.

- [ ] OPTIONAL - You can use CSS modules for styling as described [here](https://blog.logrocket.com/the-best-styling-in-react-tutorial-youve-ever-seen-676f1284b945/).

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-10-12 14:11 UTC, mikenath223 commented on src/components/App.js
> +    window.state = this.state;
- [ ] Please remove this. There's no need for `widow.state =  this.state`. It's an anti-pattern. Removing this would mean you can remove the eslint rule you disabled at the top of the module(/* eslint-disable react/destructuring-assignment */). So kindly remove that also.

2020-10-12 14:12 UTC, mikenath223 commented on src/components/App.js
> +  }
- [ ] Replace this with this instead to keep your code shorter and clean:
```
handleClick = (buttonName) => {
  this.setState(calculate(this.state, buttonName));
  }

```

2020-10-12 14:20 UTC, mikenath223 commented on src/components/ButtonPanel.js
>      <div>
- [ ] IMPORTANT - Rather than doing this. Simple put the button text and color in an array of objects and map through them. Also no need to keep repeating the color prop. Simply use this color as the default prop in the button component. To avoid repetition.
```
let buttonObj = [{
  text: '0',
  color: '#f5913e',
}]
```

2020-10-12 19:17 UTC, FrancoRosa commented
Thank you for your feedback
The required changes where made.

2020-10-13 01:24 UTC, Torres-ssf approved these changes
### Milestone approved :+1: :muscle: 
Hi there @FrancoRosa :hand: 
Awesome job on this milestone so far and also a great job implementing the requested changes.
You may merge the PR now.

Happy Coding :computer: 
**Sergio Torres**

2020-10-13 01:24 UTC, Torres-ssf commented on src/components/Button.js
> +    backgroundColor: color,
It seems the next line it's not triggering any error. Is this disable line really necessary :thinking:?

2020-10-13 02:39 UTC, FrancoRosa commented on src/components/Button.js
> +    backgroundColor: color,
That linter exception looks ugly but it was necessary.

2020-10-13 02:39 UTC, merged